// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_axi_decision_function_6 (
        ap_clk,
        ap_rst,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
output  [31:0] ap_return;
input   ap_ce;

reg[31:0] ap_return;

wire   [0:0] comparison_39_fu_230_p2;
reg   [0:0] comparison_39_reg_830;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] comparison_40_fu_236_p2;
reg   [0:0] comparison_40_reg_836;
wire   [0:0] comparison_41_fu_242_p2;
reg   [0:0] comparison_41_reg_842;
wire   [0:0] comparison_42_fu_248_p2;
reg   [0:0] comparison_42_reg_848;
wire   [0:0] comparison_43_fu_254_p2;
reg   [0:0] comparison_43_reg_854;
wire   [0:0] comparison_44_fu_260_p2;
reg   [0:0] comparison_44_reg_860;
wire   [0:0] comparison_45_fu_266_p2;
reg   [0:0] comparison_45_reg_866;
wire   [0:0] comparison_46_fu_272_p2;
reg   [0:0] comparison_46_reg_872;
wire   [0:0] comparison_47_fu_278_p2;
reg   [0:0] comparison_47_reg_878;
wire   [0:0] comparison_48_fu_284_p2;
reg   [0:0] comparison_48_reg_884;
wire   [0:0] activation_92_fu_398_p2;
reg   [0:0] activation_92_reg_889;
wire   [0:0] or_ln148_31_fu_474_p2;
reg   [0:0] or_ln148_31_reg_895;
wire   [2:0] select_ln148_31_fu_480_p3;
reg   [2:0] select_ln148_31_reg_901;
wire    ap_block_pp0_stage0;
wire   [0:0] comparison_fu_188_p2;
wire   [0:0] comparison_33_fu_194_p2;
wire   [0:0] activation_fu_290_p2;
wire   [0:0] xor_ln135_fu_302_p2;
wire   [0:0] comparison_34_fu_200_p2;
wire   [0:0] activation_81_fu_296_p2;
wire   [0:0] xor_ln135_21_fu_320_p2;
wire   [0:0] comparison_35_fu_206_p2;
wire   [0:0] activation_84_fu_326_p2;
wire   [0:0] xor_ln135_22_fu_338_p2;
wire   [0:0] comparison_36_fu_212_p2;
wire   [0:0] activation_85_fu_332_p2;
wire   [0:0] xor_ln135_23_fu_356_p2;
wire   [0:0] comparison_37_fu_218_p2;
wire   [0:0] activation_87_fu_350_p2;
wire   [0:0] xor_ln135_24_fu_374_p2;
wire   [0:0] comparison_38_fu_224_p2;
wire   [0:0] activation_89_fu_368_p2;
wire   [0:0] xor_ln135_25_fu_392_p2;
wire   [0:0] activation_111_fu_308_p2;
wire   [0:0] or_ln148_fu_404_p2;
wire   [0:0] activation_112_fu_314_p2;
wire   [1:0] zext_ln148_fu_410_p1;
wire   [0:0] or_ln148_27_fu_414_p2;
wire   [0:0] activation_113_fu_344_p2;
wire   [1:0] select_ln148_fu_420_p3;
wire   [1:0] select_ln148_28_fu_434_p3;
wire   [0:0] or_ln148_28_fu_428_p2;
wire   [0:0] activation_114_fu_362_p2;
wire   [2:0] zext_ln148_4_fu_442_p1;
wire   [0:0] or_ln148_29_fu_446_p2;
wire   [0:0] activation_115_fu_380_p2;
wire   [2:0] select_ln148_29_fu_452_p3;
wire   [0:0] or_ln148_30_fu_460_p2;
wire   [0:0] activation_116_fu_386_p2;
wire   [2:0] select_ln148_30_fu_466_p3;
wire   [0:0] xor_ln135_26_fu_492_p2;
wire   [0:0] activation_93_fu_488_p2;
wire   [0:0] xor_ln135_27_fu_507_p2;
wire   [0:0] activation_96_fu_512_p2;
wire   [0:0] xor_ln135_28_fu_523_p2;
wire   [0:0] activation_97_fu_518_p2;
wire   [0:0] xor_ln135_29_fu_539_p2;
wire   [0:0] activation_100_fu_544_p2;
wire   [0:0] xor_ln135_30_fu_555_p2;
wire   [0:0] activation_102_fu_560_p2;
wire   [0:0] xor_ln135_31_fu_571_p2;
wire   [0:0] activation_103_fu_566_p2;
wire   [0:0] xor_ln135_32_fu_587_p2;
wire   [0:0] activation_105_fu_582_p2;
wire   [0:0] xor_ln135_33_fu_603_p2;
wire   [0:0] activation_108_fu_608_p2;
wire   [0:0] xor_ln135_34_fu_619_p2;
wire   [0:0] and_ln133_fu_624_p2;
wire   [0:0] activation_117_fu_497_p2;
wire   [2:0] select_ln148_32_fu_640_p3;
wire   [0:0] or_ln148_32_fu_635_p2;
wire   [0:0] activation_118_fu_502_p2;
wire   [3:0] zext_ln148_5_fu_646_p1;
wire   [0:0] or_ln148_33_fu_650_p2;
wire   [0:0] activation_119_fu_528_p2;
wire   [3:0] select_ln148_33_fu_656_p3;
wire   [0:0] or_ln148_34_fu_664_p2;
wire   [0:0] activation_120_fu_534_p2;
wire   [3:0] select_ln148_34_fu_670_p3;
wire   [0:0] or_ln148_35_fu_678_p2;
wire   [0:0] activation_121_fu_550_p2;
wire   [3:0] select_ln148_35_fu_684_p3;
wire   [0:0] or_ln148_36_fu_692_p2;
wire   [0:0] activation_122_fu_576_p2;
wire   [3:0] select_ln148_36_fu_698_p3;
wire   [0:0] or_ln148_37_fu_706_p2;
wire   [0:0] activation_123_fu_592_p2;
wire   [3:0] select_ln148_37_fu_712_p3;
wire   [0:0] or_ln148_38_fu_720_p2;
wire   [0:0] activation_124_fu_598_p2;
wire   [3:0] select_ln148_38_fu_726_p3;
wire   [0:0] or_ln148_39_fu_734_p2;
wire   [0:0] activation_125_fu_614_p2;
wire   [3:0] select_ln148_39_fu_740_p3;
wire   [3:0] select_ln148_40_fu_754_p3;
wire   [0:0] or_ln148_40_fu_748_p2;
wire   [0:0] activation_126_fu_629_p2;
wire   [4:0] zext_ln148_6_fu_762_p1;
wire   [0:0] or_ln148_41_fu_766_p2;
wire   [4:0] select_ln148_41_fu_772_p3;
wire   [4:0] agg_result_fu_788_p19;
wire   [31:0] agg_result_fu_788_p20;
reg    ap_ce_reg;
reg   [31:0] ap_return_int_reg;

myproject_axi_mux_185_32_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_185_32_1_0_U13(
    .din0(32'd76324),
    .din1(32'd39554),
    .din2(32'd50752),
    .din3(32'd40538),
    .din4(32'd35330),
    .din5(32'd25100),
    .din6(32'd12449),
    .din7(32'd7364),
    .din8(32'd62011),
    .din9(32'd1112),
    .din10(32'd4294962372),
    .din11(32'd7645),
    .din12(32'd20461),
    .din13(32'd32776),
    .din14(32'd989),
    .din15(32'd28275),
    .din16(32'd7295),
    .din17(32'd4294856635),
    .din18(agg_result_fu_788_p19),
    .dout(agg_result_fu_788_p20)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_92_reg_889 <= activation_92_fu_398_p2;
        comparison_39_reg_830 <= comparison_39_fu_230_p2;
        comparison_40_reg_836 <= comparison_40_fu_236_p2;
        comparison_41_reg_842 <= comparison_41_fu_242_p2;
        comparison_42_reg_848 <= comparison_42_fu_248_p2;
        comparison_43_reg_854 <= comparison_43_fu_254_p2;
        comparison_44_reg_860 <= comparison_44_fu_260_p2;
        comparison_45_reg_866 <= comparison_45_fu_266_p2;
        comparison_46_reg_872 <= comparison_46_fu_272_p2;
        comparison_47_reg_878 <= comparison_47_fu_278_p2;
        comparison_48_reg_884 <= comparison_48_fu_284_p2;
        or_ln148_31_reg_895 <= or_ln148_31_fu_474_p2;
        select_ln148_31_reg_901 <= select_ln148_31_fu_480_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= agg_result_fu_788_p20;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = agg_result_fu_788_p20;
    end else begin
        ap_return = 'bx;
    end
end

assign activation_100_fu_544_p2 = (xor_ln135_29_fu_539_p2 & activation_97_fu_518_p2);

assign activation_102_fu_560_p2 = (xor_ln135_30_fu_555_p2 & activation_100_fu_544_p2);

assign activation_103_fu_566_p2 = (comparison_44_reg_860 & activation_102_fu_560_p2);

assign activation_105_fu_582_p2 = (comparison_45_reg_866 & activation_103_fu_566_p2);

assign activation_108_fu_608_p2 = (xor_ln135_33_fu_603_p2 & activation_105_fu_582_p2);

assign activation_111_fu_308_p2 = (xor_ln135_fu_302_p2 & activation_fu_290_p2);

assign activation_112_fu_314_p2 = (comparison_34_fu_200_p2 & activation_81_fu_296_p2);

assign activation_113_fu_344_p2 = (xor_ln135_22_fu_338_p2 & activation_84_fu_326_p2);

assign activation_114_fu_362_p2 = (xor_ln135_23_fu_356_p2 & activation_85_fu_332_p2);

assign activation_115_fu_380_p2 = (xor_ln135_24_fu_374_p2 & activation_87_fu_350_p2);

assign activation_116_fu_386_p2 = (comparison_38_fu_224_p2 & activation_89_fu_368_p2);

assign activation_117_fu_497_p2 = (xor_ln135_26_fu_492_p2 & activation_92_reg_889);

assign activation_118_fu_502_p2 = (comparison_40_reg_836 & activation_93_fu_488_p2);

assign activation_119_fu_528_p2 = (xor_ln135_28_fu_523_p2 & activation_96_fu_512_p2);

assign activation_120_fu_534_p2 = (comparison_42_reg_848 & activation_97_fu_518_p2);

assign activation_121_fu_550_p2 = (comparison_43_reg_854 & activation_100_fu_544_p2);

assign activation_122_fu_576_p2 = (xor_ln135_31_fu_571_p2 & activation_102_fu_560_p2);

assign activation_123_fu_592_p2 = (xor_ln135_32_fu_587_p2 & activation_103_fu_566_p2);

assign activation_124_fu_598_p2 = (comparison_46_reg_872 & activation_105_fu_582_p2);

assign activation_125_fu_614_p2 = (comparison_47_reg_878 & activation_108_fu_608_p2);

assign activation_126_fu_629_p2 = (and_ln133_fu_624_p2 & activation_108_fu_608_p2);

assign activation_81_fu_296_p2 = (comparison_33_fu_194_p2 & activation_fu_290_p2);

assign activation_84_fu_326_p2 = (xor_ln135_21_fu_320_p2 & activation_81_fu_296_p2);

assign activation_85_fu_332_p2 = (comparison_35_fu_206_p2 & activation_84_fu_326_p2);

assign activation_87_fu_350_p2 = (comparison_36_fu_212_p2 & activation_85_fu_332_p2);

assign activation_89_fu_368_p2 = (comparison_37_fu_218_p2 & activation_87_fu_350_p2);

assign activation_92_fu_398_p2 = (xor_ln135_25_fu_392_p2 & activation_89_fu_368_p2);

assign activation_93_fu_488_p2 = (comparison_39_reg_830 & activation_92_reg_889);

assign activation_96_fu_512_p2 = (xor_ln135_27_fu_507_p2 & activation_93_fu_488_p2);

assign activation_97_fu_518_p2 = (comparison_41_reg_842 & activation_96_fu_512_p2);

assign activation_fu_290_p2 = (comparison_fu_188_p2 ^ 1'd1);

assign agg_result_fu_788_p19 = ((or_ln148_41_fu_766_p2[0:0] == 1'b1) ? select_ln148_41_fu_772_p3 : 5'd17);

assign and_ln133_fu_624_p2 = (xor_ln135_34_fu_619_p2 & comparison_48_reg_884);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign comparison_33_fu_194_p2 = (($signed(p_read8) < $signed(32'd64823)) ? 1'b1 : 1'b0);

assign comparison_34_fu_200_p2 = (($signed(p_read3) < $signed(32'd4294885911)) ? 1'b1 : 1'b0);

assign comparison_35_fu_206_p2 = (($signed(p_read9) < $signed(32'd76028)) ? 1'b1 : 1'b0);

assign comparison_36_fu_212_p2 = (($signed(p_read3) < $signed(32'd86291)) ? 1'b1 : 1'b0);

assign comparison_37_fu_218_p2 = (($signed(p_read7) < $signed(32'd79823)) ? 1'b1 : 1'b0);

assign comparison_38_fu_224_p2 = (($signed(p_read9) < $signed(32'd4294888683)) ? 1'b1 : 1'b0);

assign comparison_39_fu_230_p2 = (($signed(p_read4) < $signed(32'd76125)) ? 1'b1 : 1'b0);

assign comparison_40_fu_236_p2 = (($signed(p_read7) < $signed(32'd4294827644)) ? 1'b1 : 1'b0);

assign comparison_41_fu_242_p2 = (($signed(p_read6) < $signed(32'd93474)) ? 1'b1 : 1'b0);

assign comparison_42_fu_248_p2 = (($signed(p_read6) < $signed(32'd4294884002)) ? 1'b1 : 1'b0);

assign comparison_43_fu_254_p2 = (($signed(p_read4) < $signed(32'd4294844043)) ? 1'b1 : 1'b0);

assign comparison_44_fu_260_p2 = (($signed(p_read2) < $signed(32'd136592)) ? 1'b1 : 1'b0);

assign comparison_45_fu_266_p2 = (($signed(p_read1) < $signed(32'd151190)) ? 1'b1 : 1'b0);

assign comparison_46_fu_272_p2 = (($signed(p_read2) < $signed(32'd4294833473)) ? 1'b1 : 1'b0);

assign comparison_47_fu_278_p2 = (($signed(p_read1) < $signed(32'd4294820389)) ? 1'b1 : 1'b0);

assign comparison_48_fu_284_p2 = (($signed(p_read5) < $signed(32'd4294827893)) ? 1'b1 : 1'b0);

assign comparison_fu_188_p2 = (($signed(p_read8) < $signed(32'd4294871776)) ? 1'b1 : 1'b0);

assign or_ln148_27_fu_414_p2 = (or_ln148_fu_404_p2 | activation_112_fu_314_p2);

assign or_ln148_28_fu_428_p2 = (or_ln148_27_fu_414_p2 | activation_113_fu_344_p2);

assign or_ln148_29_fu_446_p2 = (or_ln148_28_fu_428_p2 | activation_114_fu_362_p2);

assign or_ln148_30_fu_460_p2 = (or_ln148_29_fu_446_p2 | activation_115_fu_380_p2);

assign or_ln148_31_fu_474_p2 = (or_ln148_30_fu_460_p2 | activation_116_fu_386_p2);

assign or_ln148_32_fu_635_p2 = (or_ln148_31_reg_895 | activation_117_fu_497_p2);

assign or_ln148_33_fu_650_p2 = (or_ln148_32_fu_635_p2 | activation_118_fu_502_p2);

assign or_ln148_34_fu_664_p2 = (or_ln148_33_fu_650_p2 | activation_119_fu_528_p2);

assign or_ln148_35_fu_678_p2 = (or_ln148_34_fu_664_p2 | activation_120_fu_534_p2);

assign or_ln148_36_fu_692_p2 = (or_ln148_35_fu_678_p2 | activation_121_fu_550_p2);

assign or_ln148_37_fu_706_p2 = (or_ln148_36_fu_692_p2 | activation_122_fu_576_p2);

assign or_ln148_38_fu_720_p2 = (or_ln148_37_fu_706_p2 | activation_123_fu_592_p2);

assign or_ln148_39_fu_734_p2 = (or_ln148_38_fu_720_p2 | activation_124_fu_598_p2);

assign or_ln148_40_fu_748_p2 = (or_ln148_39_fu_734_p2 | activation_125_fu_614_p2);

assign or_ln148_41_fu_766_p2 = (or_ln148_40_fu_748_p2 | activation_126_fu_629_p2);

assign or_ln148_fu_404_p2 = (comparison_fu_188_p2 | activation_111_fu_308_p2);

assign select_ln148_28_fu_434_p3 = ((or_ln148_27_fu_414_p2[0:0] == 1'b1) ? select_ln148_fu_420_p3 : 2'd3);

assign select_ln148_29_fu_452_p3 = ((or_ln148_28_fu_428_p2[0:0] == 1'b1) ? zext_ln148_4_fu_442_p1 : 3'd4);

assign select_ln148_30_fu_466_p3 = ((or_ln148_29_fu_446_p2[0:0] == 1'b1) ? select_ln148_29_fu_452_p3 : 3'd5);

assign select_ln148_31_fu_480_p3 = ((or_ln148_30_fu_460_p2[0:0] == 1'b1) ? select_ln148_30_fu_466_p3 : 3'd6);

assign select_ln148_32_fu_640_p3 = ((or_ln148_31_reg_895[0:0] == 1'b1) ? select_ln148_31_reg_901 : 3'd7);

assign select_ln148_33_fu_656_p3 = ((or_ln148_32_fu_635_p2[0:0] == 1'b1) ? zext_ln148_5_fu_646_p1 : 4'd8);

assign select_ln148_34_fu_670_p3 = ((or_ln148_33_fu_650_p2[0:0] == 1'b1) ? select_ln148_33_fu_656_p3 : 4'd9);

assign select_ln148_35_fu_684_p3 = ((or_ln148_34_fu_664_p2[0:0] == 1'b1) ? select_ln148_34_fu_670_p3 : 4'd10);

assign select_ln148_36_fu_698_p3 = ((or_ln148_35_fu_678_p2[0:0] == 1'b1) ? select_ln148_35_fu_684_p3 : 4'd11);

assign select_ln148_37_fu_712_p3 = ((or_ln148_36_fu_692_p2[0:0] == 1'b1) ? select_ln148_36_fu_698_p3 : 4'd12);

assign select_ln148_38_fu_726_p3 = ((or_ln148_37_fu_706_p2[0:0] == 1'b1) ? select_ln148_37_fu_712_p3 : 4'd13);

assign select_ln148_39_fu_740_p3 = ((or_ln148_38_fu_720_p2[0:0] == 1'b1) ? select_ln148_38_fu_726_p3 : 4'd14);

assign select_ln148_40_fu_754_p3 = ((or_ln148_39_fu_734_p2[0:0] == 1'b1) ? select_ln148_39_fu_740_p3 : 4'd15);

assign select_ln148_41_fu_772_p3 = ((or_ln148_40_fu_748_p2[0:0] == 1'b1) ? zext_ln148_6_fu_762_p1 : 5'd16);

assign select_ln148_fu_420_p3 = ((or_ln148_fu_404_p2[0:0] == 1'b1) ? zext_ln148_fu_410_p1 : 2'd2);

assign xor_ln135_21_fu_320_p2 = (comparison_34_fu_200_p2 ^ 1'd1);

assign xor_ln135_22_fu_338_p2 = (comparison_35_fu_206_p2 ^ 1'd1);

assign xor_ln135_23_fu_356_p2 = (comparison_36_fu_212_p2 ^ 1'd1);

assign xor_ln135_24_fu_374_p2 = (comparison_37_fu_218_p2 ^ 1'd1);

assign xor_ln135_25_fu_392_p2 = (comparison_38_fu_224_p2 ^ 1'd1);

assign xor_ln135_26_fu_492_p2 = (comparison_39_reg_830 ^ 1'd1);

assign xor_ln135_27_fu_507_p2 = (comparison_40_reg_836 ^ 1'd1);

assign xor_ln135_28_fu_523_p2 = (comparison_41_reg_842 ^ 1'd1);

assign xor_ln135_29_fu_539_p2 = (comparison_42_reg_848 ^ 1'd1);

assign xor_ln135_30_fu_555_p2 = (comparison_43_reg_854 ^ 1'd1);

assign xor_ln135_31_fu_571_p2 = (comparison_44_reg_860 ^ 1'd1);

assign xor_ln135_32_fu_587_p2 = (comparison_45_reg_866 ^ 1'd1);

assign xor_ln135_33_fu_603_p2 = (comparison_46_reg_872 ^ 1'd1);

assign xor_ln135_34_fu_619_p2 = (comparison_47_reg_878 ^ 1'd1);

assign xor_ln135_fu_302_p2 = (comparison_33_fu_194_p2 ^ 1'd1);

assign zext_ln148_4_fu_442_p1 = select_ln148_28_fu_434_p3;

assign zext_ln148_5_fu_646_p1 = select_ln148_32_fu_640_p3;

assign zext_ln148_6_fu_762_p1 = select_ln148_40_fu_754_p3;

assign zext_ln148_fu_410_p1 = activation_fu_290_p2;

endmodule //myproject_axi_decision_function_6
