// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_axi_decision_function_12 (
        ap_ready,
        p_read1,
        p_read2,
        ap_return
);


output   ap_ready;
input  [31:0] p_read1;
input  [31:0] p_read2;
output  [31:0] ap_return;

wire   [0:0] comparison_fu_42_p2;
wire   [0:0] comparison_42_fu_48_p2;
wire   [0:0] activation_fu_54_p2;
wire   [0:0] activation_59_fu_60_p2;
wire   [0:0] or_ln208_fu_66_p2;
wire   [1:0] zext_ln208_fu_72_p1;
wire   [1:0] agg_result_fu_84_p4;
wire   [31:0] agg_result_fu_84_p5;

myproject_axi_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U89(
    .din0(32'd74730),
    .din1(32'd31153),
    .din2(32'd4294961723),
    .din3(agg_result_fu_84_p4),
    .dout(agg_result_fu_84_p5)
);

assign activation_59_fu_60_p2 = (comparison_42_fu_48_p2 & activation_fu_54_p2);

assign activation_fu_54_p2 = (comparison_fu_42_p2 ^ 1'd1);

assign agg_result_fu_84_p4 = ((or_ln208_fu_66_p2[0:0] == 1'b1) ? zext_ln208_fu_72_p1 : 2'd2);

assign ap_ready = 1'b1;

assign ap_return = agg_result_fu_84_p5;

assign comparison_42_fu_48_p2 = (($signed(p_read1) < $signed(32'd4294894727)) ? 1'b1 : 1'b0);

assign comparison_fu_42_p2 = (($signed(p_read2) < $signed(32'd4294848747)) ? 1'b1 : 1'b0);

assign or_ln208_fu_66_p2 = (comparison_fu_42_p2 | activation_59_fu_60_p2);

assign zext_ln208_fu_72_p1 = activation_fu_54_p2;

endmodule //myproject_axi_decision_function_12
