-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_axi_decision_function_5 is
port (
    ap_ready : OUT STD_LOGIC;
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of myproject_axi_decision_function_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_FFFEE987 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111101110100110000111";
    constant ap_const_lv32_FFFE8605 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111101000011000000101";
    constant ap_const_lv32_1C6C9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000011100011011001001";
    constant ap_const_lv32_FFFDD497 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111011101010010010111";
    constant ap_const_lv32_FFFF2F16 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111110010111100010110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv32_25C53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000100101110001010011";
    constant ap_const_lv32_1A8FC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000011010100011111100";
    constant ap_const_lv32_20DC6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000100000110111000110";
    constant ap_const_lv32_A909 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000001010100100001001";
    constant ap_const_lv32_87AD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000001000011110101101";
    constant ap_const_lv32_FFFF9817 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111001100000010111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal comparison_fu_68_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal comparison_11_fu_74_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal comparison_12_fu_80_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_2_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal activation_21_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal comparison_13_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln195_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln193_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal comparison_14_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln193_7_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal activation_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal activation_22_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln208_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln208_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal activation_23_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln208_fu_164_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln208_6_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln208_fu_174_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln208_6_fu_188_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln208_7_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal activation_24_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln208_2_fu_196_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln208_8_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln208_7_fu_206_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal agg_result_fu_222_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal agg_result_fu_222_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_axi_mux_63_32_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mux_63_32_1_1_x_U44 : component myproject_axi_mux_63_32_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_25C53,
        din1 => ap_const_lv32_1A8FC,
        din2 => ap_const_lv32_20DC6,
        din3 => ap_const_lv32_A909,
        din4 => ap_const_lv32_87AD,
        din5 => ap_const_lv32_FFFF9817,
        din6 => agg_result_fu_222_p7,
        dout => agg_result_fu_222_p8);




    activation_21_fu_98_p2 <= (comparison_fu_68_p2 xor ap_const_lv1_1);
    activation_22_fu_122_p2 <= (xor_ln195_2_fu_116_p2 and activation_21_fu_98_p2);
    activation_23_fu_134_p2 <= (comparison_fu_68_p2 and and_ln193_fu_128_p2);
    activation_24_fu_146_p2 <= (comparison_12_fu_80_p2 and and_ln193_7_fu_140_p2);
    activation_fu_104_p2 <= (comparison_fu_68_p2 and comparison_11_fu_74_p2);
    agg_result_fu_222_p7 <= 
        select_ln208_7_fu_206_p3 when (or_ln208_8_fu_200_p2(0) = '1') else 
        ap_const_lv3_5;
    and_ln193_7_fu_140_p2 <= (comparison_14_fu_92_p2 and activation_21_fu_98_p2);
    and_ln193_fu_128_p2 <= (xor_ln195_fu_110_p2 and comparison_13_fu_86_p2);
    ap_ready <= ap_const_logic_1;
    ap_return <= agg_result_fu_222_p8;
    comparison_11_fu_74_p2 <= "1" when (signed(p_read1) < signed(ap_const_lv32_FFFE8605)) else "0";
    comparison_12_fu_80_p2 <= "1" when (signed(p_read3) < signed(ap_const_lv32_1C6C9)) else "0";
    comparison_13_fu_86_p2 <= "1" when (signed(p_read2) < signed(ap_const_lv32_FFFDD497)) else "0";
    comparison_14_fu_92_p2 <= "1" when (signed(p_read3) < signed(ap_const_lv32_FFFF2F16)) else "0";
    comparison_fu_68_p2 <= "1" when (signed(p_read2) < signed(ap_const_lv32_FFFEE987)) else "0";
    or_ln208_6_fu_168_p2 <= (or_ln208_fu_152_p2 or activation_23_fu_134_p2);
    or_ln208_7_fu_182_p2 <= (comparison_fu_68_p2 or activation_22_fu_122_p2);
    or_ln208_8_fu_200_p2 <= (or_ln208_7_fu_182_p2 or activation_24_fu_146_p2);
    or_ln208_fu_152_p2 <= (activation_fu_104_p2 or activation_22_fu_122_p2);
    select_ln208_6_fu_188_p3 <= 
        select_ln208_fu_174_p3 when (or_ln208_6_fu_168_p2(0) = '1') else 
        ap_const_lv2_3;
    select_ln208_7_fu_206_p3 <= 
        zext_ln208_2_fu_196_p1 when (or_ln208_7_fu_182_p2(0) = '1') else 
        ap_const_lv3_4;
    select_ln208_fu_174_p3 <= 
        zext_ln208_fu_164_p1 when (or_ln208_fu_152_p2(0) = '1') else 
        ap_const_lv2_2;
    xor_ln195_2_fu_116_p2 <= (comparison_12_fu_80_p2 xor ap_const_lv1_1);
    xor_ln195_fu_110_p2 <= (comparison_11_fu_74_p2 xor ap_const_lv1_1);
    xor_ln208_fu_158_p2 <= (ap_const_lv1_1 xor activation_fu_104_p2);
    zext_ln208_2_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln208_6_fu_188_p3),3));
    zext_ln208_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln208_fu_158_p2),2));
end behav;
