// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_axi_decision_function_19 (
        ap_ready,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return
);


output   ap_ready;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
output  [31:0] ap_return;

wire   [0:0] comparison_fu_70_p2;
wire   [0:0] comparison_201_fu_76_p2;
wire   [0:0] comparison_202_fu_82_p2;
wire   [0:0] and_ln193_fu_106_p2;
wire   [0:0] comparison_203_fu_88_p2;
wire   [0:0] xor_ln195_fu_100_p2;
wire   [0:0] and_ln193_60_fu_118_p2;
wire   [0:0] activation_251_fu_112_p2;
wire   [0:0] activation_fu_94_p2;
wire   [0:0] or_ln208_fu_130_p2;
wire   [1:0] zext_ln208_fu_136_p1;
wire   [0:0] or_ln208_61_fu_140_p2;
wire   [0:0] activation_252_fu_124_p2;
wire   [1:0] select_ln208_fu_146_p3;
wire   [1:0] select_ln208_85_fu_160_p3;
wire   [0:0] or_ln208_62_fu_154_p2;
wire   [2:0] zext_ln208_19_fu_168_p1;
wire   [2:0] agg_result_fu_180_p6;
wire   [31:0] agg_result_fu_180_p7;
wire    ap_ce_reg;

myproject_axi_mux_53_32_1_1_x1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_53_32_1_1_x1_U250(
    .din0(32'd55948),
    .din1(32'd4294961994),
    .din2(32'd51401),
    .din3(32'd10498),
    .din4(32'd51356),
    .din5(agg_result_fu_180_p6),
    .dout(agg_result_fu_180_p7)
);

assign activation_251_fu_112_p2 = (comparison_201_fu_76_p2 & and_ln193_fu_106_p2);

assign activation_252_fu_124_p2 = (comparison_fu_70_p2 & and_ln193_60_fu_118_p2);

assign activation_fu_94_p2 = (comparison_fu_70_p2 ^ 1'd1);

assign agg_result_fu_180_p6 = ((or_ln208_62_fu_154_p2[0:0] == 1'b1) ? zext_ln208_19_fu_168_p1 : 3'd4);

assign and_ln193_60_fu_118_p2 = (xor_ln195_fu_100_p2 & comparison_203_fu_88_p2);

assign and_ln193_fu_106_p2 = (comparison_fu_70_p2 & comparison_202_fu_82_p2);

assign ap_ready = 1'b1;

assign ap_return = agg_result_fu_180_p7;

assign comparison_201_fu_76_p2 = (($signed(p_read4) < $signed(32'd61589)) ? 1'b1 : 1'b0);

assign comparison_202_fu_82_p2 = (($signed(p_read1) < $signed(32'd132835)) ? 1'b1 : 1'b0);

assign comparison_203_fu_88_p2 = (($signed(p_read3) < $signed(32'd65386)) ? 1'b1 : 1'b0);

assign comparison_fu_70_p2 = (($signed(p_read2) < $signed(32'd135470)) ? 1'b1 : 1'b0);

assign or_ln208_61_fu_140_p2 = (comparison_201_fu_76_p2 | activation_fu_94_p2);

assign or_ln208_62_fu_154_p2 = (or_ln208_61_fu_140_p2 | activation_252_fu_124_p2);

assign or_ln208_fu_130_p2 = (activation_fu_94_p2 | activation_251_fu_112_p2);

assign select_ln208_85_fu_160_p3 = ((or_ln208_61_fu_140_p2[0:0] == 1'b1) ? select_ln208_fu_146_p3 : 2'd3);

assign select_ln208_fu_146_p3 = ((or_ln208_fu_130_p2[0:0] == 1'b1) ? zext_ln208_fu_136_p1 : 2'd2);

assign xor_ln195_fu_100_p2 = (comparison_201_fu_76_p2 ^ 1'd1);

assign zext_ln208_19_fu_168_p1 = select_ln208_85_fu_160_p3;

assign zext_ln208_fu_136_p1 = comparison_fu_70_p2;

endmodule //myproject_axi_decision_function_19
