// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_axi_decision_function_1 (
        ap_ready,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return
);


output   ap_ready;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
output  [31:0] ap_return;

wire   [0:0] comparison_77_fu_88_p2;
wire   [0:0] comparison_fu_82_p2;
wire   [0:0] comparison_78_fu_94_p2;
wire   [0:0] activation_212_fu_118_p2;
wire   [0:0] xor_ln135_fu_124_p2;
wire   [0:0] comparison_79_fu_100_p2;
wire   [0:0] activation_213_fu_130_p2;
wire   [0:0] xor_ln135_1_fu_142_p2;
wire   [0:0] comparison_80_fu_106_p2;
wire   [0:0] activation_fu_148_p2;
wire   [0:0] xor_ln135_2_fu_154_p2;
wire   [0:0] comparison_81_fu_112_p2;
wire   [0:0] and_ln133_fu_166_p2;
wire   [0:0] xor_ln148_fu_178_p2;
wire   [1:0] zext_ln148_fu_184_p1;
wire   [0:0] or_ln148_fu_188_p2;
wire   [0:0] activation_217_fu_136_p2;
wire   [1:0] select_ln148_fu_194_p3;
wire   [1:0] select_ln148_1_fu_208_p3;
wire   [0:0] or_ln148_1_fu_202_p2;
wire   [0:0] activation_218_fu_160_p2;
wire   [2:0] zext_ln148_1_fu_216_p1;
wire   [0:0] or_ln148_2_fu_220_p2;
wire   [0:0] activation_219_fu_172_p2;
wire   [2:0] select_ln148_2_fu_226_p3;
wire   [0:0] or_ln148_3_fu_234_p2;
wire   [2:0] select_ln148_3_fu_240_p3;
wire   [2:0] agg_result_fu_256_p8;
wire   [31:0] agg_result_fu_256_p9;

myproject_axi_mux_73_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_73_32_1_1_U48(
    .din0(32'd38605),
    .din1(32'd29025),
    .din2(32'd54752),
    .din3(32'd28188),
    .din4(32'd9970),
    .din5(32'd48755),
    .din6(32'd4294926860),
    .din7(agg_result_fu_256_p8),
    .dout(agg_result_fu_256_p9)
);

assign activation_212_fu_118_p2 = (comparison_fu_82_p2 & comparison_77_fu_88_p2);

assign activation_213_fu_130_p2 = (xor_ln135_fu_124_p2 & activation_212_fu_118_p2);

assign activation_217_fu_136_p2 = (comparison_79_fu_100_p2 & activation_213_fu_130_p2);

assign activation_218_fu_160_p2 = (xor_ln135_2_fu_154_p2 & activation_fu_148_p2);

assign activation_219_fu_172_p2 = (comparison_80_fu_106_p2 & and_ln133_fu_166_p2);

assign activation_fu_148_p2 = (xor_ln135_1_fu_142_p2 & activation_213_fu_130_p2);

assign agg_result_fu_256_p8 = ((or_ln148_3_fu_234_p2[0:0] == 1'b1) ? select_ln148_3_fu_240_p3 : 3'd6);

assign and_ln133_fu_166_p2 = (comparison_81_fu_112_p2 & activation_fu_148_p2);

assign ap_ready = 1'b1;

assign ap_return = agg_result_fu_256_p9;

assign comparison_77_fu_88_p2 = (($signed(p_read3) < $signed(32'd57997)) ? 1'b1 : 1'b0);

assign comparison_78_fu_94_p2 = (($signed(p_read3) < $signed(32'd4294849312)) ? 1'b1 : 1'b0);

assign comparison_79_fu_100_p2 = (($signed(p_read4) < $signed(32'd4294896171)) ? 1'b1 : 1'b0);

assign comparison_80_fu_106_p2 = (($signed(p_read4) < $signed(32'd52484)) ? 1'b1 : 1'b0);

assign comparison_81_fu_112_p2 = (($signed(p_read1) < $signed(32'd4294849785)) ? 1'b1 : 1'b0);

assign comparison_fu_82_p2 = (($signed(p_read2) < $signed(32'd64469)) ? 1'b1 : 1'b0);

assign or_ln148_1_fu_202_p2 = (or_ln148_fu_188_p2 | activation_217_fu_136_p2);

assign or_ln148_2_fu_220_p2 = (or_ln148_1_fu_202_p2 | activation_218_fu_160_p2);

assign or_ln148_3_fu_234_p2 = (or_ln148_2_fu_220_p2 | activation_219_fu_172_p2);

assign or_ln148_fu_188_p2 = (xor_ln148_fu_178_p2 | comparison_78_fu_94_p2);

assign select_ln148_1_fu_208_p3 = ((or_ln148_fu_188_p2[0:0] == 1'b1) ? select_ln148_fu_194_p3 : 2'd3);

assign select_ln148_2_fu_226_p3 = ((or_ln148_1_fu_202_p2[0:0] == 1'b1) ? zext_ln148_1_fu_216_p1 : 3'd4);

assign select_ln148_3_fu_240_p3 = ((or_ln148_2_fu_220_p2[0:0] == 1'b1) ? select_ln148_2_fu_226_p3 : 3'd5);

assign select_ln148_fu_194_p3 = ((activation_212_fu_118_p2[0:0] == 1'b1) ? 2'd2 : zext_ln148_fu_184_p1);

assign xor_ln135_1_fu_142_p2 = (comparison_79_fu_100_p2 ^ 1'd1);

assign xor_ln135_2_fu_154_p2 = (comparison_80_fu_106_p2 ^ 1'd1);

assign xor_ln135_fu_124_p2 = (comparison_78_fu_94_p2 ^ 1'd1);

assign xor_ln148_fu_178_p2 = (1'd1 ^ activation_212_fu_118_p2);

assign zext_ln148_1_fu_216_p1 = select_ln148_1_fu_208_p3;

assign zext_ln148_fu_184_p1 = comparison_fu_82_p2;

endmodule //myproject_axi_decision_function_1
