// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_axi_decision_function_33 (
        ap_ready,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return
);


output   ap_ready;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
output  [31:0] ap_return;

wire   [0:0] comparison_fu_70_p2;
wire   [0:0] comparison_116_fu_76_p2;
wire   [0:0] comparison_117_fu_82_p2;
wire   [0:0] and_ln193_fu_106_p2;
wire   [0:0] comparison_118_fu_88_p2;
wire   [0:0] xor_ln195_fu_100_p2;
wire   [0:0] and_ln193_105_fu_118_p2;
wire   [0:0] activation_146_fu_112_p2;
wire   [0:0] activation_fu_94_p2;
wire   [0:0] or_ln208_fu_130_p2;
wire   [1:0] zext_ln208_fu_136_p1;
wire   [0:0] or_ln208_71_fu_140_p2;
wire   [0:0] activation_147_fu_124_p2;
wire   [1:0] select_ln208_fu_146_p3;
wire   [1:0] select_ln208_89_fu_160_p3;
wire   [0:0] or_ln208_72_fu_154_p2;
wire   [2:0] zext_ln208_20_fu_168_p1;
wire   [2:0] agg_result_fu_180_p6;
wire   [31:0] agg_result_fu_180_p7;
wire    ap_ce_reg;

myproject_axi_mux_53_32_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_53_32_1_1_x_U164(
    .din0(32'd79963),
    .din1(32'd53853),
    .din2(32'd10801),
    .din3(32'd4294955073),
    .din4(32'd19887),
    .din5(agg_result_fu_180_p6),
    .dout(agg_result_fu_180_p7)
);

assign activation_146_fu_112_p2 = (comparison_116_fu_76_p2 & and_ln193_fu_106_p2);

assign activation_147_fu_124_p2 = (comparison_fu_70_p2 & and_ln193_105_fu_118_p2);

assign activation_fu_94_p2 = (comparison_fu_70_p2 ^ 1'd1);

assign agg_result_fu_180_p6 = ((or_ln208_72_fu_154_p2[0:0] == 1'b1) ? zext_ln208_20_fu_168_p1 : 3'd4);

assign and_ln193_105_fu_118_p2 = (xor_ln195_fu_100_p2 & comparison_118_fu_88_p2);

assign and_ln193_fu_106_p2 = (comparison_fu_70_p2 & comparison_117_fu_82_p2);

assign ap_ready = 1'b1;

assign ap_return = agg_result_fu_180_p7;

assign comparison_116_fu_76_p2 = (($signed(p_read2) < $signed(32'd4294911883)) ? 1'b1 : 1'b0);

assign comparison_117_fu_82_p2 = (($signed(p_read4) < $signed(32'd4294936309)) ? 1'b1 : 1'b0);

assign comparison_118_fu_88_p2 = (($signed(p_read1) < $signed(32'd58586)) ? 1'b1 : 1'b0);

assign comparison_fu_70_p2 = (($signed(p_read3) < $signed(32'd139229)) ? 1'b1 : 1'b0);

assign or_ln208_71_fu_140_p2 = (comparison_116_fu_76_p2 | activation_fu_94_p2);

assign or_ln208_72_fu_154_p2 = (or_ln208_71_fu_140_p2 | activation_147_fu_124_p2);

assign or_ln208_fu_130_p2 = (activation_fu_94_p2 | activation_146_fu_112_p2);

assign select_ln208_89_fu_160_p3 = ((or_ln208_71_fu_140_p2[0:0] == 1'b1) ? select_ln208_fu_146_p3 : 2'd3);

assign select_ln208_fu_146_p3 = ((or_ln208_fu_130_p2[0:0] == 1'b1) ? zext_ln208_fu_136_p1 : 2'd2);

assign xor_ln195_fu_100_p2 = (comparison_116_fu_76_p2 ^ 1'd1);

assign zext_ln208_20_fu_168_p1 = select_ln208_89_fu_160_p3;

assign zext_ln208_fu_136_p1 = comparison_fu_70_p2;

endmodule //myproject_axi_decision_function_33
