// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_axi_decision_function_8 (
        ap_ready,
        p_read1,
        ap_return
);


output   ap_ready;
input  [31:0] p_read1;
output  [31:0] ap_return;

wire   [0:0] comparison_fu_34_p2;
wire   [0:0] comparison_4_fu_40_p2;
wire   [0:0] activation_fu_46_p2;
wire   [0:0] or_ln208_fu_52_p2;
wire   [1:0] zext_ln208_fu_58_p1;
wire   [1:0] agg_result_fu_70_p4;
wire   [31:0] agg_result_fu_70_p5;

myproject_axi_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U99(
    .din0(32'd23742),
    .din1(32'd12196),
    .din2(32'd4294944519),
    .din3(agg_result_fu_70_p4),
    .dout(agg_result_fu_70_p5)
);

assign activation_fu_46_p2 = (comparison_fu_34_p2 ^ 1'd1);

assign agg_result_fu_70_p4 = ((or_ln208_fu_52_p2[0:0] == 1'b1) ? zext_ln208_fu_58_p1 : 2'd2);

assign ap_ready = 1'b1;

assign ap_return = agg_result_fu_70_p5;

assign comparison_4_fu_40_p2 = (($signed(p_read1) < $signed(32'd4294946473)) ? 1'b1 : 1'b0);

assign comparison_fu_34_p2 = (($signed(p_read1) < $signed(32'd48363)) ? 1'b1 : 1'b0);

assign or_ln208_fu_52_p2 = (comparison_4_fu_40_p2 | activation_fu_46_p2);

assign zext_ln208_fu_58_p1 = comparison_fu_34_p2;

endmodule //myproject_axi_decision_function_8
