// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_axi_myproject (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        ap_return
);


output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
output  [31:0] ap_return;

wire    s_V_decision_function_7_fu_108_ap_ready;
wire   [31:0] s_V_decision_function_7_fu_108_ap_return;
wire    s_V_1_decision_function_6_fu_116_ap_ready;
wire   [31:0] s_V_1_decision_function_6_fu_116_ap_return;
wire    s_V_2_decision_function_5_fu_126_ap_ready;
wire   [31:0] s_V_2_decision_function_5_fu_126_ap_return;
wire    s_V_3_decision_function_4_fu_134_ap_ready;
wire   [31:0] s_V_3_decision_function_4_fu_134_ap_return;
wire    s_V_4_decision_function_3_fu_142_ap_ready;
wire   [31:0] s_V_4_decision_function_3_fu_142_ap_return;
wire    s_V_5_decision_function_2_fu_150_ap_ready;
wire   [31:0] s_V_5_decision_function_2_fu_150_ap_return;
wire    s_V_6_decision_function_1_fu_158_ap_ready;
wire   [31:0] s_V_6_decision_function_1_fu_158_ap_return;
wire    s_V_7_decision_function_fu_168_ap_ready;
wire   [31:0] s_V_7_decision_function_fu_168_ap_return;
wire   [31:0] add_ln712_1_fu_182_p2;
wire   [31:0] add_ln712_fu_176_p2;
wire   [31:0] add_ln712_4_fu_200_p2;
wire   [31:0] add_ln712_5_fu_206_p2;
wire   [31:0] add_ln712_3_fu_194_p2;
wire   [31:0] add_ln712_6_fu_212_p2;
wire   [31:0] add_ln712_2_fu_188_p2;

myproject_axi_decision_function_7 s_V_decision_function_7_fu_108(
    .ap_ready(s_V_decision_function_7_fu_108_ap_ready),
    .p_read1(p_read1),
    .p_read2(p_read5),
    .ap_return(s_V_decision_function_7_fu_108_ap_return)
);

myproject_axi_decision_function_6 s_V_1_decision_function_6_fu_116(
    .ap_ready(s_V_1_decision_function_6_fu_116_ap_ready),
    .p_read1(p_read2),
    .p_read2(p_read5),
    .p_read3(p_read7),
    .ap_return(s_V_1_decision_function_6_fu_116_ap_return)
);

myproject_axi_decision_function_5 s_V_2_decision_function_5_fu_126(
    .ap_ready(s_V_2_decision_function_5_fu_126_ap_ready),
    .p_read1(p_read2),
    .p_read2(p_read4),
    .ap_return(s_V_2_decision_function_5_fu_126_ap_return)
);

myproject_axi_decision_function_4 s_V_3_decision_function_4_fu_134(
    .ap_ready(s_V_3_decision_function_4_fu_134_ap_ready),
    .p_read1(p_read7),
    .p_read2(p_read8),
    .ap_return(s_V_3_decision_function_4_fu_134_ap_return)
);

myproject_axi_decision_function_3 s_V_4_decision_function_3_fu_142(
    .ap_ready(s_V_4_decision_function_3_fu_142_ap_ready),
    .p_read1(p_read3),
    .p_read2(p_read9),
    .ap_return(s_V_4_decision_function_3_fu_142_ap_return)
);

myproject_axi_decision_function_2 s_V_5_decision_function_2_fu_150(
    .ap_ready(s_V_5_decision_function_2_fu_150_ap_ready),
    .p_read1(p_read),
    .p_read2(p_read6),
    .ap_return(s_V_5_decision_function_2_fu_150_ap_return)
);

myproject_axi_decision_function_1 s_V_6_decision_function_1_fu_158(
    .ap_ready(s_V_6_decision_function_1_fu_158_ap_ready),
    .p_read1(p_read5),
    .p_read2(p_read6),
    .p_read3(p_read9),
    .ap_return(s_V_6_decision_function_1_fu_158_ap_return)
);

myproject_axi_decision_function s_V_7_decision_function_fu_168(
    .ap_ready(s_V_7_decision_function_fu_168_ap_ready),
    .p_read1(p_read2),
    .p_read2(p_read4),
    .ap_return(s_V_7_decision_function_fu_168_ap_return)
);

assign add_ln712_1_fu_182_p2 = (s_V_2_decision_function_5_fu_126_ap_return + s_V_3_decision_function_4_fu_134_ap_return);

assign add_ln712_2_fu_188_p2 = (add_ln712_1_fu_182_p2 + add_ln712_fu_176_p2);

assign add_ln712_3_fu_194_p2 = (s_V_4_decision_function_3_fu_142_ap_return + s_V_5_decision_function_2_fu_150_ap_return);

assign add_ln712_4_fu_200_p2 = (s_V_7_decision_function_fu_168_ap_return + 32'd1965);

assign add_ln712_5_fu_206_p2 = (add_ln712_4_fu_200_p2 + s_V_6_decision_function_1_fu_158_ap_return);

assign add_ln712_6_fu_212_p2 = (add_ln712_5_fu_206_p2 + add_ln712_3_fu_194_p2);

assign add_ln712_fu_176_p2 = (s_V_1_decision_function_6_fu_116_ap_return + s_V_decision_function_7_fu_108_ap_return);

assign ap_ready = 1'b1;

assign ap_return = (add_ln712_6_fu_212_p2 + add_ln712_2_fu_188_p2);

endmodule //myproject_axi_myproject
