AcceleratorConfig:
  Driver: python
  Interface: axi_stream
  Precision:
    Input: float
    Output: float
Backend: VivadoAccelerator
ClockPeriod: 7
HLSConfig:
  Model:
    Precision: ap_fixed<32,16>
    ReuseFactor: 1
IOType: io_parallel
InputData: wrapper_heavily_unbalanced/X_test.npy
OutputDir: wrapper_heavily_unbalanced
OutputPredictions: wrapper_heavily_unbalanced/y_hls.npy
Part: xczu3eg-sbva484-1-e
ProjectName: myproject
Stamp: 96C2FB29
XilinxPart: xc7z020clg400-1
