-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_axi is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_r_TVALID : IN STD_LOGIC;
    in_r_TREADY : OUT STD_LOGIC;
    in_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_r_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_r_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_r_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_r_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_TVALID : OUT STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC;
    out_r_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_r_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_r_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of myproject_axi is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject_axi_myproject_axi,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.040500,HLS_SYN_LAT=27,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=42914,HLS_SYN_LUT=206614,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_FFFFFFE8 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111101000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv6_39 : STD_LOGIC_VECTOR (5 downto 0) := "111001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_FFFFFFE7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111100111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal out_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_myproject_fu_209_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal out_local_V_reg_651 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal s_reg_658 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_i_i_fu_271_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_i_i_reg_664 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal tobool_i_i_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_i_i_reg_669 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal tmp_V_fu_281_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_V_reg_674 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln997_fu_304_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln997_reg_679 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1011_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1011_reg_685 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1011_fu_418_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1011_reg_690 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln996_fu_426_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln996_reg_695 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_done : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_idle : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_ready : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_r_TREADY : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_9_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_9_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_8_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_8_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_7_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_7_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_6_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_6_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_5_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_5_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_4_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_3_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_2_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_1_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_tmp_last_V_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_tmp_last_V_1_out_ap_vld : STD_LOGIC;
    signal grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_Result_3_fu_286_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_fu_296_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal lsb_index_fu_310_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_316_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln1000_fu_332_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln1000_fu_336_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln1000_fu_342_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln1000_fu_346_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln1002_fu_352_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1002_1_fu_358_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln1002_fu_364_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_376_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_390_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1002_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln999_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1002_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln999_fu_410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1002_1_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1012_fu_437_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1010_fu_434_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1012_fu_442_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1011_fu_452_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1011_fu_457_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln1011_fu_461_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln1012_fu_446_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_fu_467_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1014_fu_474_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_2_fu_477_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_5_fu_483_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_Result_s_fu_497_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1017_fu_513_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln996_fu_505_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1017_fu_518_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1015_fu_493_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_524_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_5_fu_531_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_fu_543_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal regslice_both_out_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state14 : BOOLEAN;
    signal regslice_both_in_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_r_TVALID_int_regslice : STD_LOGIC;
    signal in_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_r_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_r_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_r_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_r_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_TVALID_int_regslice : STD_LOGIC;
    signal out_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_r_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_axi_myproject_axi_Pipeline_VITIS_LOOP_21_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_r_TVALID : IN STD_LOGIC;
        in_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_r_TREADY : OUT STD_LOGIC;
        in_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_r_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_r_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_r_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_r_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_local_V_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_9_out_ap_vld : OUT STD_LOGIC;
        in_local_V_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_8_out_ap_vld : OUT STD_LOGIC;
        in_local_V_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_7_out_ap_vld : OUT STD_LOGIC;
        in_local_V_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_6_out_ap_vld : OUT STD_LOGIC;
        in_local_V_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_5_out_ap_vld : OUT STD_LOGIC;
        in_local_V_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_4_out_ap_vld : OUT STD_LOGIC;
        in_local_V_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_3_out_ap_vld : OUT STD_LOGIC;
        in_local_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_2_out_ap_vld : OUT STD_LOGIC;
        in_local_V_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_1_out_ap_vld : OUT STD_LOGIC;
        in_local_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_local_V_out_ap_vld : OUT STD_LOGIC;
        tmp_last_V_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        tmp_last_V_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component myproject_axi_myproject IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component myproject_axi_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180 : component myproject_axi_myproject_axi_Pipeline_VITIS_LOOP_21_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start,
        ap_done => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_done,
        ap_idle => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_idle,
        ap_ready => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_ready,
        in_r_TVALID => in_r_TVALID_int_regslice,
        in_r_TDATA => in_r_TDATA_int_regslice,
        in_r_TREADY => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_r_TREADY,
        in_r_TKEEP => in_r_TKEEP_int_regslice,
        in_r_TSTRB => in_r_TSTRB_int_regslice,
        in_r_TUSER => in_r_TUSER_int_regslice,
        in_r_TLAST => in_r_TLAST_int_regslice,
        in_r_TID => in_r_TID_int_regslice,
        in_r_TDEST => in_r_TDEST_int_regslice,
        in_local_V_9_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_9_out,
        in_local_V_9_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_9_out_ap_vld,
        in_local_V_8_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_8_out,
        in_local_V_8_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_8_out_ap_vld,
        in_local_V_7_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_7_out,
        in_local_V_7_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_7_out_ap_vld,
        in_local_V_6_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_6_out,
        in_local_V_6_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_6_out_ap_vld,
        in_local_V_5_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_5_out,
        in_local_V_5_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_5_out_ap_vld,
        in_local_V_4_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_4_out,
        in_local_V_4_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_4_out_ap_vld,
        in_local_V_3_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_3_out,
        in_local_V_3_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_3_out_ap_vld,
        in_local_V_2_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_2_out,
        in_local_V_2_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_2_out_ap_vld,
        in_local_V_1_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_1_out,
        in_local_V_1_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_1_out_ap_vld,
        in_local_V_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_out,
        in_local_V_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_out_ap_vld,
        tmp_last_V_1_out => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_tmp_last_V_1_out,
        tmp_last_V_1_out_ap_vld => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_tmp_last_V_1_out_ap_vld);

    grp_myproject_fu_209 : component myproject_axi_myproject
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        p_read => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_8_out,
        p_read1 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_7_out,
        p_read2 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_6_out,
        p_read3 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_5_out,
        p_read4 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_4_out,
        p_read5 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_3_out,
        p_read6 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_2_out,
        p_read7 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_1_out,
        p_read8 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_out,
        p_read9 => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_local_V_9_out,
        ap_return => grp_myproject_fu_209_ap_return);

    regslice_both_in_r_V_data_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TDATA,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_data_V_U_ack_in,
        data_out => in_r_TDATA_int_regslice,
        vld_out => in_r_TVALID_int_regslice,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_data_V_U_apdone_blk);

    regslice_both_in_r_V_keep_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TKEEP,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_keep_V_U_ack_in,
        data_out => in_r_TKEEP_int_regslice,
        vld_out => regslice_both_in_r_V_keep_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_keep_V_U_apdone_blk);

    regslice_both_in_r_V_strb_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TSTRB,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_strb_V_U_ack_in,
        data_out => in_r_TSTRB_int_regslice,
        vld_out => regslice_both_in_r_V_strb_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_strb_V_U_apdone_blk);

    regslice_both_in_r_V_user_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TUSER,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_user_V_U_ack_in,
        data_out => in_r_TUSER_int_regslice,
        vld_out => regslice_both_in_r_V_user_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_user_V_U_apdone_blk);

    regslice_both_in_r_V_last_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TLAST,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_last_V_U_ack_in,
        data_out => in_r_TLAST_int_regslice,
        vld_out => regslice_both_in_r_V_last_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_last_V_U_apdone_blk);

    regslice_both_in_r_V_id_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TID,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_id_V_U_ack_in,
        data_out => in_r_TID_int_regslice,
        vld_out => regslice_both_in_r_V_id_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_id_V_U_apdone_blk);

    regslice_both_in_r_V_dest_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TDEST,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_dest_V_U_ack_in,
        data_out => in_r_TDEST_int_regslice,
        vld_out => regslice_both_in_r_V_dest_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_dest_V_U_apdone_blk);

    regslice_both_out_r_V_data_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_r_TDATA_int_regslice,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => out_r_TREADY_int_regslice,
        data_out => out_r_TDATA,
        vld_out => regslice_both_out_r_V_data_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_data_V_U_apdone_blk);

    regslice_both_out_r_V_keep_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_keep_V_U_ack_in_dummy,
        data_out => out_r_TKEEP,
        vld_out => regslice_both_out_r_V_keep_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_keep_V_U_apdone_blk);

    regslice_both_out_r_V_strb_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_strb_V_U_ack_in_dummy,
        data_out => out_r_TSTRB,
        vld_out => regslice_both_out_r_V_strb_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_strb_V_U_apdone_blk);

    regslice_both_out_r_V_user_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_user_V_U_ack_in_dummy,
        data_out => out_r_TUSER,
        vld_out => regslice_both_out_r_V_user_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_user_V_U_apdone_blk);

    regslice_both_out_r_V_last_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_tmp_last_V_1_out,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_last_V_U_ack_in_dummy,
        data_out => out_r_TLAST,
        vld_out => regslice_both_out_r_V_last_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_last_V_U_apdone_blk);

    regslice_both_out_r_V_id_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_id_V_U_ack_in_dummy,
        data_out => out_r_TID,
        vld_out => regslice_both_out_r_V_id_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_id_V_U_apdone_blk);

    regslice_both_out_r_V_dest_V_U : component myproject_axi_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_dest_V_U_ack_in_dummy,
        data_out => out_r_TDEST,
        vld_out => regslice_both_out_r_V_dest_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_ready = ap_const_logic_1)) then 
                    grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                icmp_ln1011_reg_685 <= icmp_ln1011_fu_398_p2;
                select_ln1011_reg_690 <= select_ln1011_fu_418_p3;
                sub_ln997_reg_679 <= sub_ln997_fu_304_p2;
                tmp_V_reg_674 <= tmp_V_fu_281_p3;
                tobool_i_i_reg_669 <= tobool_i_i_fu_276_p2;
                trunc_ln996_reg_695 <= trunc_ln996_fu_426_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                out_local_V_reg_651 <= grp_myproject_fu_209_ap_return;
                s_reg_658 <= grp_myproject_fu_209_ap_return(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((s_reg_658 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                sub_i_i_reg_664 <= sub_i_i_fu_271_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state13, ap_CS_fsm_state14, grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_done, ap_CS_fsm_state3, regslice_both_out_r_V_data_V_U_apdone_blk, out_r_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((out_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if ((not(((out_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_out_r_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    LD_fu_543_p1 <= p_Result_5_fu_531_p5(32 - 1 downto 0);
    add_ln1011_fu_452_p2 <= std_logic_vector(unsigned(sub_ln997_reg_679) + unsigned(ap_const_lv32_FFFFFFE7));
    add_ln1017_fu_518_p2 <= std_logic_vector(unsigned(sub_ln1017_fu_513_p2) + unsigned(select_ln996_fu_505_p3));
    and_ln1002_1_fu_404_p2 <= (xor_ln1002_fu_384_p2 and p_Result_4_fu_390_p3);
    and_ln1002_fu_364_p2 <= (tmp_V_fu_281_p3 and or_ln1002_1_fu_358_p2);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(out_r_TREADY_int_regslice)
    begin
        if ((out_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state14_blk_assign_proc : process(regslice_both_out_r_V_data_V_U_apdone_blk, out_r_TREADY_int_regslice)
    begin
        if (((out_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_out_r_V_data_V_U_apdone_blk = ap_const_logic_1))) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_done)
    begin
        if ((grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state14_assign_proc : process(regslice_both_out_r_V_data_V_U_apdone_blk, out_r_TREADY_int_regslice)
    begin
                ap_block_state14 <= ((out_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_out_r_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start <= grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_ap_start_reg;
    icmp_ln1002_fu_370_p2 <= "0" when (and_ln1002_fu_364_p2 = ap_const_lv32_0) else "1";
    icmp_ln1011_fu_398_p2 <= "1" when (signed(lsb_index_fu_310_p2) > signed(ap_const_lv32_0)) else "0";
    icmp_ln999_fu_326_p2 <= "1" when (signed(tmp_fu_316_p4) > signed(ap_const_lv31_0)) else "0";
    in_r_TREADY <= regslice_both_in_r_V_data_V_U_ack_in;

    in_r_TREADY_int_regslice_assign_proc : process(grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_r_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_r_TREADY_int_regslice <= grp_myproject_axi_Pipeline_VITIS_LOOP_21_1_fu_180_in_r_TREADY;
        else 
            in_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    
    l_fu_296_p3_proc : process(p_Result_3_fu_286_p4)
    begin
        l_fu_296_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if p_Result_3_fu_286_p4(i) = '1' then
                l_fu_296_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    lsb_index_fu_310_p2 <= std_logic_vector(unsigned(sub_ln997_fu_304_p2) + unsigned(ap_const_lv32_FFFFFFE8));
    lshr_ln1000_fu_346_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv32_FFFFFFFF),to_integer(unsigned('0' & zext_ln1000_fu_342_p1(31-1 downto 0)))));
    lshr_ln1011_fu_461_p2 <= std_logic_vector(shift_right(unsigned(zext_ln1010_fu_434_p1),to_integer(unsigned('0' & zext_ln1011_fu_457_p1(31-1 downto 0)))));
    m_2_fu_477_p2 <= std_logic_vector(unsigned(m_fu_467_p3) + unsigned(zext_ln1014_fu_474_p1));
    m_5_fu_483_p4 <= m_2_fu_477_p2(63 downto 1);
    m_fu_467_p3 <= 
        lshr_ln1011_fu_461_p2 when (icmp_ln1011_reg_685(0) = '1') else 
        shl_ln1012_fu_446_p2;
    or_ln1002_1_fu_358_p2 <= (shl_ln1002_fu_352_p2 or lshr_ln1000_fu_346_p2);

    out_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state14, out_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            out_r_TDATA_blk_n <= out_r_TREADY_int_regslice;
        else 
            out_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_TDATA_int_regslice <= 
        ap_const_lv32_0 when (tobool_i_i_reg_669(0) = '1') else 
        LD_fu_543_p1;
    out_r_TVALID <= regslice_both_out_r_V_data_V_U_vld_out;

    out_r_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state13, out_r_TREADY_int_regslice)
    begin
        if (((out_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            out_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    
    p_Result_3_fu_286_p4_proc : process(tmp_V_fu_281_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable p_Result_3_fu_286_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := tmp_V_fu_281_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for p_Result_3_fu_286_p4_i in 0 to 32-1 loop
                v0_cpy(p_Result_3_fu_286_p4_i) := tmp_V_fu_281_p3(32-1-p_Result_3_fu_286_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        p_Result_3_fu_286_p4 <= resvalue(32-1 downto 0);
    end process;

    p_Result_4_fu_390_p3 <= tmp_V_fu_281_p3(to_integer(unsigned(lsb_index_fu_310_p2)) downto to_integer(unsigned(lsb_index_fu_310_p2))) when (to_integer(unsigned(lsb_index_fu_310_p2)) >= 0 and to_integer(unsigned(lsb_index_fu_310_p2)) <=31) else "-";
    p_Result_5_fu_531_p5 <= (zext_ln1015_fu_493_p1(63 downto 32) & tmp_1_fu_524_p3 & zext_ln1015_fu_493_p1(22 downto 0));
    p_Result_s_fu_497_p3 <= m_2_fu_477_p2(25 downto 25);
    select_ln1011_fu_418_p3 <= 
        select_ln999_fu_410_p3 when (icmp_ln1011_fu_398_p2(0) = '1') else 
        and_ln1002_1_fu_404_p2;
    select_ln996_fu_505_p3 <= 
        ap_const_lv8_7F when (p_Result_s_fu_497_p3(0) = '1') else 
        ap_const_lv8_7E;
    select_ln999_fu_410_p3 <= 
        icmp_ln1002_fu_370_p2 when (icmp_ln999_fu_326_p2(0) = '1') else 
        p_Result_4_fu_390_p3;
    shl_ln1002_fu_352_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & lsb_index_fu_310_p2(31-1 downto 0)))));
    shl_ln1012_fu_446_p2 <= std_logic_vector(shift_left(unsigned(zext_ln1010_fu_434_p1),to_integer(unsigned('0' & zext_ln1012_fu_442_p1(31-1 downto 0)))));
    sub_i_i_fu_271_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(out_local_V_reg_651));
    sub_ln1000_fu_336_p2 <= std_logic_vector(signed(ap_const_lv6_39) - signed(trunc_ln1000_fu_332_p1));
    sub_ln1012_fu_437_p2 <= std_logic_vector(unsigned(ap_const_lv32_19) - unsigned(sub_ln997_reg_679));
    sub_ln1017_fu_513_p2 <= std_logic_vector(unsigned(ap_const_lv8_10) - unsigned(trunc_ln996_reg_695));
    sub_ln997_fu_304_p2 <= std_logic_vector(unsigned(ap_const_lv32_20) - unsigned(l_fu_296_p3));
    tmp_1_fu_524_p3 <= (s_reg_658 & add_ln1017_fu_518_p2);
    tmp_2_fu_376_p3 <= lsb_index_fu_310_p2(31 downto 31);
    tmp_V_fu_281_p3 <= 
        sub_i_i_reg_664 when (s_reg_658(0) = '1') else 
        out_local_V_reg_651;
    tmp_fu_316_p4 <= lsb_index_fu_310_p2(31 downto 1);
    tobool_i_i_fu_276_p2 <= "1" when (out_local_V_reg_651 = ap_const_lv32_0) else "0";
    trunc_ln1000_fu_332_p1 <= sub_ln997_fu_304_p2(6 - 1 downto 0);
    trunc_ln996_fu_426_p1 <= l_fu_296_p3(8 - 1 downto 0);
    xor_ln1002_fu_384_p2 <= (tmp_2_fu_376_p3 xor ap_const_lv1_1);
    zext_ln1000_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln1000_fu_336_p2),32));
    zext_ln1010_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_reg_674),64));
    zext_ln1011_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1011_fu_452_p2),64));
    zext_ln1012_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln1012_fu_437_p2),64));
    zext_ln1014_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1011_reg_690),64));
    zext_ln1015_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_5_fu_483_p4),64));
end behav;
